=== JuanJoseg80/evaluacion/src/biblioteca.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name = "biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "libro"  maxOccurs="unbounded" minOccurs="0" >
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="titulo" maxOccurs="unbounded" type="xs:string"/>


                            <xs:element name="autor" maxOccurs="unbounded"   >
                                <xs:complexType >


                                    <xs:sequence>
                                        <xs:element name="nombre"  maxOccurs="unbounded" type="xs:string"/>

                                        <xs:element name="apellido" maxOccurs="unbounded" type="xs:string">
                                            <xs:simpleType >
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([a-z])+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>




                                    </xs:sequence>





                                    <xs:attribute type="xs:positiveInteger" name="id" />
                                    <xs:attribute type="xs:string" name="ciudad"/>
                                    <xs:attribute type="xs:string" name="pais"/>
                                    <xs:attribute type="xs:positiveInteger" name="telefono"/>
                                    <xs:attribute type="xs:string" name="correo"/>



                                </xs:complexType >









                            </xs:element>




                            <xs:element name="fecha" maxOccurs="unbounded" >
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="anyo">
                                            <xs:simpleType >
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minInclusive value="1990"/>
                                                    <xs:maxInclusive value="2020"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                    </xs:sequence>

                                </xs:complexType>
                            </xs:element>

                            <xs:element name="editor" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="precio" maxOccurs="unbounded" type="xs:integer"/>





                        </xs:sequence>
                        <xs:attribute type="xs:string" name="categoria" />
                        <xs:attribute type="xs:string" name="enstock"/>
                        <xs:attribute type="xs:string" name="CP"  />
                    </xs:complexType>


                </xs:element>
            </xs:sequence>

        </xs:complexType>
    </xs:element>
</xs:schema>

=== JuanJoseg80/evaluacion/src/biblioteca.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type ="text/xsl" href="biblioteca.xsl"?>
<!DOCTYPE biblioteca>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="biblioteca.xsd">


    <libro categoria="ficcion" enstock="true" CP="ESP">
        <titulo>Los hombres que no amaban a las mujeres</titulo>
        <autor id= "10014562" ciudad ="berlin"   pais ="alemania" telefono ="1235" correo ="sjdnhs@mail" >
            <nombre>marcos</nombre>
            <apellido>salmanca</apellido>

        </autor>
        <fecha>
            <anyo>2020</anyo>
        </fecha>
        <editor>Destino</editor>
        <precio> 2232</precio>
    </libro>

    <libro categoria="noficcion"  CP="ESP">
        <titulo>Java a trav√©s de ejemplos</titulo>
        <autor  id ="10016564"  ciudad ="medellin"   pais ="col" telefono ="54656" correo ="skasjs@mail"  >
            <nombre>kiki</nombre>

            <apellido>gutierrez</apellido>
        </autor>
        <fecha>

            <anyo>2003</anyo>
        </fecha>
        <editor>Ra-Ma</editor>
        <precio> 2232</precio>
    </libro>






</biblioteca>
